[package]
name = "crab-fs"
version = "0.1.0"
edition = "2021"

[dependencies]
crab-fs-common = { path = "../common" }
crab-fs-repository = { path = "../repository", features = [ "fuser-traits" ] }
crab-fs-backend = { path = "../backend" }

bincode = "1.3.3"
env_logger = "0.11.5"
fuser = { version = "0.15.0", default-features = true }
libc = "0.2.165"
log = "0.4.22"
serde = { version = "1.0.215", features = ["std", "derive"] }
clap = { version = "4.5.21", features = ["cargo", "derive"] }
num-traits = "0.2.19"
rand = "0.8.5"
base64 = "0.22.1"
rand_chacha = "0.3.1"
sha2 = "0.10.8"
blake3 = "1.5.4"
backtrace = "0.3.74"
remotefs = "0.3.1"
remotefs-smb = "0.3.0"
remotefs-ssh = "0.5.0"
aes-gcm = "0.10.3"
generic-array = "1.2.0"
xts-mode = "0.5.1"
aes = "0.8.4"



[build-dependencies]
pkg-config = { version = "0.3.14", optional = true }

[features]
default = ["abi-7-28"]  # Your default ABI level
abi-7-9 = ["fuser/abi-7-9"]
abi-7-10 = ["abi-7-9", "fuser/abi-7-10"]
abi-7-11 = ["abi-7-10", "fuser/abi-7-11"]
abi-7-12 = ["abi-7-11", "fuser/abi-7-12"]
abi-7-13 = ["abi-7-12", "fuser/abi-7-13"]
abi-7-14 = ["abi-7-13", "fuser/abi-7-14"]
abi-7-15 = ["abi-7-14", "fuser/abi-7-15"]
abi-7-16 = ["abi-7-15", "fuser/abi-7-16"]
abi-7-17 = ["abi-7-16", "fuser/abi-7-17"]
abi-7-18 = ["abi-7-17", "fuser/abi-7-18"]
abi-7-19 = ["abi-7-18", "fuser/abi-7-19"]
abi-7-20 = ["abi-7-19", "fuser/abi-7-20"]
abi-7-21 = ["abi-7-20", "fuser/abi-7-21"]
abi-7-22 = ["abi-7-21", "fuser/abi-7-22"]
abi-7-23 = ["abi-7-22", "fuser/abi-7-23"]
abi-7-24 = ["abi-7-23", "fuser/abi-7-24"]
abi-7-25 = ["abi-7-24", "fuser/abi-7-25"]
abi-7-26 = ["abi-7-25", "fuser/abi-7-26"]
abi-7-27 = ["abi-7-26", "fuser/abi-7-27"]
abi-7-28 = ["abi-7-27", "fuser/abi-7-28"]
abi-7-29 = ["abi-7-28", "fuser/abi-7-29"]
abi-7-30 = ["abi-7-29", "fuser/abi-7-30"]
abi-7-31 = ["abi-7-30", "fuser/abi-7-31"]