[package]
name = "crab-fs"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
env_logger = "0.11.5"
fuser = { version = "0.15.0", features = [ "abi-7-28" ] }
libc = "0.2.165"
log = "0.4.22"
serde = { version = "1.0.215", features = ["std", "derive"] }
clap = { version = "4.5.21", features = ["cargo", "derive"] }
num-traits = "0.2.19"
rand = "0.8.5"
base64 = "0.22.1"
rand_chacha = "0.3.1"
sha2 = "0.10.8"
blake3 = "1.5.4"
backtrace = "0.3.74"
remotefs = "0.3.1"
remotefs-smb = "0.3.0"
remotefs-ssh = "0.5.0"
aes-gcm = "0.10.3"
generic-array = "1.2.0"
xts-mode = "0.5.1"
aes = "0.8.4"
crab-fs-common = { path = "../common" }
crab-fs-repository = { path = "../repository", features = [ "fuser-traits" ] }
crab-fs-backend = { path = "../backend" }

mailboxxy = "0.0.3"
async-std = "1.13.0"
smol = "2.0.2"
tempfile = "3.17.1"

[profile.release]
lto = true
strip = true

[build-dependencies]
pkg-config = { version = "0.3.14", optional = true }


[dev-dependencies]
#mailboxxy = "0.0.2"
#async-std = "1.13.0"
#smol = "2.0.2"