[package]
name = "crab-fs-common"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
num-traits = "0.2.19"
rand = "0.8.5"
libc = "0.2.165"
rand_chacha = "0.3.1"
backtrace = "0.3.74"
sha2 = "0.10.8"
remotefs = "0.3.1"